main: ch.hatbe2113.vibeeconomy.main.Main
name: VibeEconomy
author: hatbe2113
website: https://hatbe.ch
description: Teccis Economy Plugin
version: 1.0.0
api-version: 1.16
commands:
  pay:
    aliases: zahlen
  balance:
    aliases: [guthaben, money]
  bank:
    aliases: bankadmin
